### PR TITLE
Fix GitHub/GitLab state config not being honoured

### LINKED ISSUE #344: GitHub includingLabels option seems to no longer be filtering

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #344 

This was broken in https://github.com/matrix-org/matrix-hookshot/pull/330 when we started using the output of the validation function as the config passed to the connections, so any configuration not handled by that validation function would be forgotten about. This PR:

- Uses ajv to ensure that we validate every expected property
- Adds some tests to cover a small amount of GitHubRepoConnection, enough to know that this bug is fixed.

### CODE REVIEW

File: src/Connections/GithubRepo.ts [hunk 1]
```diff
@@ -107,6 +87,119 @@ const AllowedEvents: AllowedEventsNames[] = [
     "release",
 ];
 
+const ConnectionStateSchema = {
+  type: "object",
+  properties: {
+    priority: {
+        type: "number",
+        nullable: true,
```
Comment (Half-Shot) [inline src/Connections/GithubRepo.ts:95]: This would only compile after peppering the schema will these `nullables`. I suppose it's correct, but it's also naff.

File: src/Connections/GithubRepo.ts [hunk 2]
```diff
@@ -115,46 +204,29 @@ function compareEmojiStrings(e0: string, e1: string, e0Index = 0) {
...
+	static validateState(state: Record<string, unknown>, isExistingState = false): GitHubRepoConnectionState {
+        const validator = new Ajv().compile(ConnectionStateSchema);
+        if (validator(state)) {
+            // Validate ignoreHooks IF this is an incoming update (we can be less strict for existing state)
+            if (!isExistingState && state.ignoreHooks && !state.ignoreHooks.every(h => AllowedEvents.includes(h))) {
+                throw new ApiError('`ignoreHooks` must only contain allowed values', ErrCode.BadValue);
+            }
+            return state;
+        }
+        throw new ValidatorApiError(validator.errors || []);
```
Comment (tadzik) [inline src/Connections/GithubRepo.ts:222]: Curious – is there an expected scenario when validation wouldn't pass but `validator.errors` would be empty? The code is sound regardless, I just wonder if it'd happen for anything other than ajv bug.

File: src/Connections/GithubRepo.ts [hunk 3]
```diff
@@ -115,46 +204,29 @@ function compareEmojiStrings(e0: string, e1: string, e0Index = 0) {
...
 /**
  * Handles rooms connected to a github repo.
  */
 @Connection
 export class GitHubRepoConnection extends CommandConnection implements IConnection {
+
+	static validateState(state: Record<string, unknown>, isExistingState = false): GitHubRepoConnectionState {
+        const validator = new Ajv().compile(ConnectionStateSchema);
+        if (validator(state)) {
+            // Validate ignoreHooks IF this is an incoming update (we can be less strict for existing state)
```
Comment (tadzik) [inline src/Connections/GithubRepo.ts:216]: Are we only less strict then because of backwards compatibility?

File: src/Connections/GitlabRepo.ts [hunk 4]
```diff
@@ -128,11 +144,23 @@ export class GitLabRepoConnection extends CommandConnection {
     static helpMessage: (cmdPrefix?: string | undefined) => MatrixMessageContent;
     static ServiceCategory = "gitlab";
 
+	static validateState(state: Record<string, unknown>, isExistingState = false): GitLabRepoConnectionState {
+        const validator = new Ajv({ strict: false }).compile(ConnectionStateSchema);
+        if (validator(state)) {
+            // Validate ignoreHooks IF this is an incoming update (we can be less strict for existing state)
```
Comment (tadzik) [inline src/Connections/GitlabRepo.ts:150]: In this file this is already enforced by the JSON schema. Is this bit copypasted, or is the schema unnecessarily strict?

File: tests/utils/UserTokenStoreMock.ts [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+import { Api } from "@octokit/plugin-rest-endpoint-methods/dist-types/types";
+import { GitLabClient } from "../../src/Gitlab/Client";
+import { JiraClient } from "../../src/Jira/Client";
+import { JiraOAuth } from "../../src/Jira/OAuth";
+import { UserTokenStore } from "../../src/UserTokenStore";
+
+export class UserTokenStoreMock {
+    public jiraOAuth?: JiraOAuth;
+
+    public load(): Promise<void> {
```
Comment (tadzik) [inline tests/utils/UserTokenStoreMock.ts:13]: Any reason why all of these are defined at all (since they throw anyway)?

Seems like this entire Mock is actually unused (see the GithubRepoTest suggestion).

File: tests/connections/GithubRepoTest.ts [hunk 6]
```diff
@@ -0,0 +1,147 @@
...
+	const githubInstance = new GithubInstance("foo", "bar");
+	const connection = new GitHubRepoConnection(
+		ROOM_ID,
+		as,
+		GitHubRepoConnection.validateState({
+			org: "a-fake-org",
+			repo: "a-fake-repo",
+			...state,
+		}),
+		tokenStore,
```
Comment (tadzik) [inline tests/connections/GithubRepoTest.ts:56]:
```suggestion
		{} as UserTokenStore,
```
This seems to work as well, and we don't need to create (and define) a mock at all :)

File: src/Connections/GithubRepo.ts (hunk 3 above)
Comment (tadzik) [reply src/Connections/GithubRepo.ts:216]: This isn't covered by the new tests (regardless of `isExistingState`) – would be nice to have it there, and it'd be a good place for the rationale for the future reader :)

[instanbul](https://istanbul.js.org/) confirms:

image

**Review by tadzik — CHANGES_REQUESTED** [review]
Fantastic – would be great to have the tests for Gitlab as well, but I'm not going to too picky since this is already a massive improvement. Left a few nits here and there.

File: src/Connections/GithubRepo.ts (hunk 2 above)
Comment (tadzik) [reply src/Connections/GithubRepo.ts:222]: (And if that's valid ajv behaviour, it may be worth teaching ValidatorApiError's constructor to accept falsy `validator.errors` too, so that a future developer doesn't need to remember about this possibility.

File: src/Connections/GithubRepo.ts (hunk 3 above)
Comment (Half-Shot) [reply src/Connections/GithubRepo.ts:216]: >Are we only less strict then because of backwards compatibility?

Yeah, though I'm wondering if it's even worth being strict here.

File: src/Connections/GithubRepo.ts (hunk 2 above)
Comment (Half-Shot) [reply src/Connections/GithubRepo.ts:226]: I think this was just a typing bug yeah. 

>(And if that's valid ajv behaviour, it may be worth teaching ValidatorApiError's constructor to accept falsy validator.errors too, so that a future developer doesn't need to remember about this possibility.

Yep, let's do that.

File: src/Connections/GitlabRepo.ts (hunk 4 above)
Comment (Half-Shot) [reply src/Connections/GitlabRepo.ts:150]: Think I just failed to commit this actually.

**Review by tadzik — APPROVED** [review]
