### PR TITLE
Automatically reconfigure GitHub notifications when a token is updated.

### LINKED ISSUE #387: You need to toggle GitHub notifications off and on after replacing expired token
**Describe the bug**
After replacing your expired GitHub token with `github setpersonaltoken %your-token%`, notifications don't resume automatically. Instead, you need to send `github notifications toggle` twice. The bot then catches up with all missed notifications.

**To Reproduce**
1. Wait for your GitHub token to expire.
2. Create a new one and give it to Hookshot.

**Expected behavior**
Notifications are to resume immediately after giving the new token to Hookshot.

**Screenshots**
Screen Shot 2022-06-29 at 10 17 46 AM

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #387 

This makes the token store an emitter which emits an event when a token for a user is updated, allowing us to then emit a message to the watchers.

### CODE REVIEW

File: src/Bridge.ts [hunk 1]
```diff
@@ -1188,4 +1189,32 @@ export class Bridge {
         log.debug(`Set up ${roomId} as an admin room for ${adminRoom.userId}`);
         return adminRoom;
     }
+
+    private onTokenUpdated(type: string, userId: string, token: string, instanceUrl?: string) {
+        let instanceName: string|undefined;
+        if (type === "gitlab") {
+            // TODO: Refactor our API to depend on either instanceUrl or instanceName.
+            instanceName =  Object.entries(this.config.gitlab?.instances || {}).find(i => i[1].url === instanceUrl)?.[0];
```
Comment (jaller94) [inline src/Bridge.ts:1197]:
```suggestion
            instanceName =  Object.entries(this.config.gitlab?.instances || {}).find(instance => instance[1].url === instanceUrl)?.[0];
```

Comment (Half-Shot) [reply src/Bridge.ts:1197]: Very true.

File: src/Bridge.ts [hunk 2]
```diff
@@ -1188,4 +1189,32 @@ export class Bridge {
...
         return adminRoom;
     }
+
+    private onTokenUpdated(type: string, userId: string, token: string, instanceUrl?: string) {
+        let instanceName: string|undefined;
+        if (type === "gitlab") {
+            // TODO: Refactor our API to depend on either instanceUrl or instanceName.
+            instanceName =  Object.entries(this.config.gitlab?.instances || {}).find(instance => instance[1].url === instanceUrl)?.[0];
+        } else if (type === "github") {
+            // Nothing to do.
```
Comment (jaller94) [inline src/Bridge.ts:1199]:
```suggestion
            // No instanceName to get, because we always assume to use github.com
```

**Review by jaller94 — APPROVED** [review]
