### PR TITLE
Decrease connection creation concurrency when starting up

### LINKED ISSUE #608: Network failures on startup can lead to missing connections
Caused in part by #607 

We should probably retry these connections when things fail.

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #608 

This isn't really the best possible fix, but I think actually going through and eliminating all the possible ways we can fail a HTTP request on startup to be a significant effort. To avoid spinning too much time away on that, this change:

- Stops us from trying to fetch all state at once on startup at once concurrently, upsetting the homeserver. Instead, load 2 at a time. In the future we can increase this.
- Avoids `getRoomState` failures (which are probably the biggest explosion point) by retrying them on failure.

### CODE REVIEW

File: src/PromiseUtil.ts [hunk 1]
```diff
@@ -1,9 +1,17 @@
 import { Logger } from "matrix-appservice-bridge";
+import { MatrixError } from "matrix-bot-sdk";
 
 const SLEEP_TIME_MS = 250;
 const DEFAULT_RETRY = () => true;
 const log = new Logger("PromiseUtil");
 
+export function retryMatrixErrorFilter(err: unknown) {
+    if (err instanceof MatrixError && err.statusCode >= 400 && err.statusCode <= 499) {
```
Comment (jaller94) [inline src/PromiseUtil.ts:9]: It will retry, if the error isn't a MatrixError. Is that what we want?
I thought this is secifically for retrying on (temporary) server errors and rate limiting.

Are gateway timeouts MatrixErrors?

**Review by jaller94 — APPROVED** [review]

File: package.json [hunk 2]
```diff
@@ -60,6 +60,7 @@
     "mime": "^3.0.0",
     "node-emoji": "^1.11.0",
     "nyc": "^15.1.0",
+    "p-queue": "^6.6.2",
```
Comment (jaller94) [inline package.json:63]: Did yarn.lock not get updated and CI is not complaining?? 🧐

Comment (Half-Shot) [reply package.json:63]: It was already a dependency of matrix-appservice-bridge, a free one if you will :)

File: src/PromiseUtil.ts (hunk 1 above)
Comment (Half-Shot) [reply src/PromiseUtil.ts:9]: The intention is to retry non-fatal errors, i.e. we will retry 5XX errors because more often than not it's the server blowing up. Anything that's not a MatrixError is also considered temporary (we err on the side of caution).
